// (C) Mason Larobina <mason.larobina@gmail.com>
// clang -std=c99 -Wall -o a 2.c && time ./a

// === Problem 2 ===
// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:
//
//   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// Find the sum of all the even-valued terms in the sequence which do not
// exceed four million.

#include <stdio.h>

int
next_even_fib(void)
{
    static int a = 0, b = 1, c;
    /* return every third term */
    for (int i = 0; i < 3; i++) {
        c = b;
        b += a;
        a = c;
    }
    return a;
}

int
main(void)
{
    long total = 0, i;
    while ((i = next_even_fib()) < 4e6)
        total += i;
    printf("%ld\n", total);
    return 0;
}
