#!/usr/bin/python
# Mason Larobina <mason.larobina@gmail.com>

# === Problem 2 ==============================================================
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# Find the sum of all the even-valued terms in the sequence which do not
# exceed four million.
# ============================================================================

def fib_generator(a=1, b=2):
    yield a
    yield b
    while True:
        a, b  = b, a+b
        yield b

total = 0
for fib in fib_generator():
    if fib >= 4e6:
        break

    elif not fib % 2:
        total += fib

print total
